source ~/.config/tmux/colors.conf

# Colors from rose-pine/neovim palette
set -g @ACCENT_COLOR "#eb6f92"
set -g @ROSE_COLOR "#ebbcba"

# Appearance
set -ga terminal-overrides ",screen-256color*:Tc"
set-option -g default-terminal "screen-256color"
# set -g window-active-style "default"
# set -g status-bg "default"

set -g status-style "fg=#{@thm_text_variant},bg=default"
set -g status-left-length 100
set -g status-left "#[fg=#{@thm_primary},bold] #S#[fg=#{@thm_text_variant},nobold] | "
set -g window-status-current-format "#[bold] #[underscore]#I:#W"
set -g message-style "fg=#{@thm_fg},bg=default"
set -g mode-style "fg=#{@thm_inverse_primary},bg=#{@thm_primary}"
set -g pane-active-border-style "fg=#{@thm_primary},bg=default"
set -g pane-border-style 'fg=#{@thm_outline},bg=default'

# General options
set -g default-command "${SHELL}"
set -g base-index 1
set -g escape-time 0
set -g focus-events on          # Let nvim 'autoread' see external file changes
set -g history-limit 1000000
set -g renumber-windows on
set -g set-clipboard on         # Use system clipboard
set -g mouse on

# Panes behaviour
bind '"' split-window -c "#{pane_current_path}"
bind % split-window -h -c "#{pane_current_path}"

# Windows
bind c new-window -c "#{pane_current_path}"

# Vi mode
set-window-option -g mode-keys vi
bind -T copy-mode-vi v send-keys -X begin-selection
bind -T copy-mode-vi y send-keys -X copy-pipe-and-cancel 'xclip -in -selection clipboard'

# Key mappings
bind r source-file ~/.config/tmux/tmux.conf

bind C-o popup -E -d "#{pane_current_path}" -w 90% -h 90% "opencode"

# vim-like pane switching
bind -r ^ last-window
bind -r k select-pane -U
bind -r j select-pane -D
bind -r h select-pane -L
bind -r l select-pane -R
bind-key -r -T prefix M-k resize-pane -U 5
bind-key -r -T prefix M-j resize-pane -D 5
bind-key -r -T prefix M-h resize-pane -L 5
bind-key -r -T prefix M-l resize-pane -R 5
bind-key -r -T prefix C-k resize-pane -U
bind-key -r -T prefix C-j resize-pane -D
bind-key -r -T prefix C-h resize-pane -L
bind-key -r -T prefix C-l resize-pane -R
