preload = ~/Pictures/wallpapers/wallhaven-rdylgq.jpg
preload = ~/Pictures/wallpapers/delorean.png

# wallpaper = eDP-1,~/Pictures/wallpapers/wallhaven-rdylgq.jpg
# wallpaper = DP-3,~/Pictures/wallpapers/wallhaven-rdylgq.jpg

wallpaper {
    monitor =
    path = ~/Pictures/wallpapers/delorean.png
    fit_mode = cover
}
